plugins {
    id 'java'
    id 'java-library'
    id 'com.gtnewhorizons.retrofuturagradle' version '2.0.2'
}

version = project.mod_version
group = 'br.com.owfrigo.enchantselector'

base {
    archivesName = 'EnchantSelector-1.12.2'
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
        vendor.set(org.gradle.jvm.toolchain.JvmVendorSpec.AZUL)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

minecraft {
    mcVersion.set('1.12.2')
    mcpMappingChannel.set('stable')
    mcpMappingVersion.set('39')
    username.set('Developer')
}

tasks.processResources.configure {
    inputs.property 'version', project.version

    filesMatching('mcmod.info') {
        expand 'version': project.version, 'mcversion': '1.12.2'
    }
}
